version: '3.8'

services:
  backend:
    image: ruchitbhosle19/lavishescapes-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lavishescapes-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: ruchitbhosle19/lavishescapes-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lavishescapes-frontend
    ports:
      - "8500:80"
    depends_on:
      - backend
    restart: unless-stopped
